### ISSUE TITLE
sk_disk_smart_parse_attributes commented out

### ISSUE THREAD

**Issue by EllisK-L** [cholcombe973/libatasmart-sys#1]
Hey, I've been looking at using libatasmart (and by extension libatasmart-sys) in a project. I was going to add a wrapper for sk_disk_smart_parse_attributes since for my project I need to grab all attributes associated to a disk. However, I noticed you had that commented out. Is there a specific reason for doing so, or is it just unimplemented?

**Comment by cholcombe973** [comment]
I think it's just unimplemented. If I recall the reason might have been that I didn't know what to do about the callback function but it's just a guess.

**Comment by EllisK-L** [comment]
Ah okay, how would you feel about me taking a stab at implementing it?

**Comment by cholcombe973** [comment]
Yeah go for it!

**Comment by cholcombe973** [comment]
I wonder if this library would be useful https://crates.io/crates/libffi

**Comment by EllisK-L** [comment]
Thanks for the link, I'll do some reading on that. So far I've got it working to an extent, although it seems pretty ugly. I'm figuring how to to make it more like rust and less like C. I have this defined in libatasmart-sys

```rust
pub fn sk_disk_smart_parse_attributes(d: *mut SkDisk, cb: extern fn(d: *mut SkDisk, data: *const SkSmartAttributeParsedData, userdata: *mut ::libc::c_void), userdata: *mut ::libc::c_void) -> ::libc::c_int;
```

allowing me to pass in a call back function like:

```rust
extern "C" fn test_callback(d: *mut SkDisk, data: *const SkSmartAttributeParsedData, userdata: *mut c_void) {
    unsafe {
        let name = CStr::from_ptr((*data).name);
        let name_str = name.to_str().unwrap();
        println!("{name_str}");
    }
}
```
While this does *work*, it needs more work.

This is my first time doing rust wrappers, so let me know if anything sticks out as very wrong haha

**Comment by EllisK-L** [comment]
For the recent new merge, should the crate version be updated, and pushed to crates.io? Since now to get the most recent code I have to include a git link.

**Comment by cholcombe973** [comment]
Yup. I was planning on doing that and got distracted with something else. I'll push a release now.

**Comment by cholcombe973** [comment]
Alright 0.2.0 is up on crates.io now. Thanks for the PR!
